### ISSUE TITLE
new crypto issue

### ISSUE THREAD

**Issue by razeghi71** [checkiz/elixir-mongo#35]
Hi,

recently when I try to use elixir-mongo I get following error message:

```
06:09:01.242 [error] Task #PID<0.842.0> started from Quantum terminating
** (UndefinedFunctionError) function :crypto.rand_bytes/1 is undefined or private. Did you mean one of:

      * rand_seed/0
      * rand_seed/1

    (crypto) :crypto.rand_bytes(4)
    (mongo) lib/mongo_server.ex:294: Mongo.Server.gen_reqid/0
    (mongo) lib/mongo_server.ex:93: Mongo.Server.send/2
    (mongo) lib/mongo_collection.ex:109: Mongo.Collection.update/5

```

Is there any fix?

**Comment by razeghi71** [comment]
After some search, I figured out that rand_bytes function is now deprecated and we should use strong_rand_bytes instead.

**Comment by dapperAuteur** [comment]
thank you. also impacts Exlixir Phoenix Framework testing

**Comment by NucProject** [comment]
Yes, the line bold would fix
  defp gen_reqid() do
    **<<tail::24, _::1, head::7>> = :crypto.strong_rand_bytes(4)**
    <<tail::24, 0::1, head::7>>
  end

It works now
